DXPBASEDIR=/opt/dxp70
DXPSOURCEDIR=$DXPBASEDIR/src
DXPSERVERDIR=$DXPBASEDIR/server
DXPTOMCATDIR=$DXPSERVERDIR/tomcat-8.0.32
DXPDEPLOYDIR=$DXPSERVERDIR/deploy
DXPDOWNLOADSDIR=$NEXTCLOUDDIR/Downloads/dxp
DXPPATCHESDIR=$DXPDOWNLOADSDIR/patches
DXPLOGDIR=$DXPBASEDIR/log
PORTAL_EXT="${DXPSERVERDIR}/portal-ext.properties"
DXPLOG4JCONFIG=${DXPTOMCATDIR}/webapps/ROOT/WEB-INF/classes/log4j.properties


