#!/bin/bash

BASE=~/Documents/accounts/chromium
CMD="chromium-browser --user-data-dir=$BASE/$1"

if [ "$1" == "" ]; then
	chromium-browser
else
	test -d $BASE || exit 1

	if [ "$1" == "virgo" ]; then
		rm -rf $BASE/$1
		$CMD
		rm -rf $BASE/$1

	else
		if [ ! -d $BASE/$1 ]; then
			echo Only these profiles exist
			echo
			ls -1 $BASE
			echo
			echo "$BASE/$1 not found. Create it? [y / ...]"
			read -r -n1 CHOICE
			if [ "$CHOICE" == "y" ]; then
				mkdir $BASE/$1
			else
				exit 0
			fi
		fi

		$CMD

	fi
fi
