#!/bin/bash

. ~/bin/common.sh || exit 1

BASE=~/Documents/accounts/chromium
CMD="chromium-browser --user-data-dir=$BASE/$1"

if [ "$1" == "" ]; then
	chromium-browser
else
	test -d $BASE || exit 1

	if [ "$1" == "virgo" ]; then
		rm -rf $BASE/$1
		$CMD
		rm -rf $BASE/$1

	else
		if [ ! -d $BASE/$1 ]; then
			echo Only these profiles exist
			echo
			ls -1 $BASE
			echo
			confirm "$BASE/$1 not found. Create it? [y / ...]"
			mkdir $BASE/$1
		fi

		$CMD

	fi
fi
