#!/bin/bash

source ~/bin/common.sh || exit 1

isLiferayRunning

RUNNING=$?

if [ $RUNNING -eq 1 ]; then

	echo "Leave the gogo shell with disconnect. Do not use logout, exit etc., this will shutdown DXP!"
	echo Press any key to continue ...

	read -n1 joepie

	# telnet localhost 11311
	telnet localhost 11312

else

	echo Liferay is not running

fi
