#!/bin/bash

source ~/bin/common.sh || exit 1
source $CREDSFILE

checkedPushd ~/compose-yOUlearn

if [ "$1" == "up" ]; then
	docker-compose up -d
elif [ "$1" == "down" ]; then
	docker-compose down
else
	echo "Usage @0 [up|down]"
	popd
	exit 1
fi

popd
