#!/bin/bash
#
# Tomcat auto-start
#
# description: Auto-starts tomcat
# processname: tomcat
# pidfile: /var/run/tomcat.pid
# see http://www.howtogeek.com/howto/linux/installing-tomcat-6-on-ubuntu/

### BEGIN INIT INFO
# Provides:       tomcat
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start:  2 3 5
# Default-Stop:
# Description:    Start the Tomcat application server
### END INIT INFO

#
# RVB 30-05-2017
# Lees tomcat logging (catalina.out) om het correct starten van
# Liferay te waarborgen...
#

#
# JAL 20170908
# Create tempdir needed for Bamboo deployment. Stop when startup /
# shutdown is complete (named pipe). Refactor
#

LIFERAY_DIR=/usr/local/liferay
PROPS=$LIFERAY_DIR/portal-ext.properties
BAMBOO_TEMPDIR=$LIFERAY_DIR/tmp_dlwo
TOMCAT_DIR=$LIFERAY_DIR/tomcat-7.0.62
TOMCAT_BINDIR=$TOMCAT_DIR/bin
TOMCAT_LOG=$TOMCAT_DIR/logs/catalina.out
TOMCAT_USER=tomcat
NAP=5

cleanup() {
  echo "Cleanup and recreate tempdirs"
  rm -rf $TOMCAT_DIR/work
  mkdir $TOMCAT_DIR/work
  chown tomcat:tomcat $TOMCAT_DIR/work
  rm -rf $TOMCAT_DIR/temp
  mkdir $TOMCAT_DIR/temp
  chown tomcat:tomcat $TOMCAT_DIR/temp
  rm -rf $BAMBOO_TEMPDIR
  mkdir $BAMBOO_TEMPDIR
  chown tomcat:tomcat $BAMBOO_TEMPDIR
  sudo chmod g+s $BAMBOO_TEMPDIR
}

waitforit() {
  echo -e "Waiting for $1 to complete"
	NOW=$(($(date +%s%N)/1000000))
  FIFO="$TMP/tomcat_$NOW"
  mkfifo $FIFO || exit 1
  tail -f $TOMCAT_LOG > $FIFO &
  TAIL_PID=$!
  grep -m 1 "$2" $FIFO
  kill $TAIL_PID
  rm $FIFO
  echo -e "$1 completed."
}

usage() {
	echo "Usage: $0 start | stop | restart | debug"
}

if ! [ $(id -u) = 0 ]; then
	echo "Run $0 as root"
	exit 1
fi

TOMCAT_PID=`ps -ef | grep tomcat | grep java | awk '{print $2}'`

case $1 in

start)
	if [ -n "$TOMCAT_PID" ]; then
		echo Tomcat is already running on pid $TOMCAT_PID
	else
  	sudo -u $TOMCAT_USER sh $TOMCAT_BINDIR/startup.sh
  	waitforit "startup" "INFO: Server startup in "
	fi
  ;;

debug)
	if [ -n "$TOMCAT_PID" ]; then
		echo Tomcat is already running on pid $TOMCAT_PID
	else
		export JPDA_ADDRESS=8000
		export JPDA_TRANSPORT=dt_socket 
		sudo -u $TOMCAT_USER sh $TOMCAT_BINDIR/startup.sh jpda
		waitforit "startup" "INFO: Server startup in "
	fi
  ;;
                                          
stop)
	if [ -n "$TOMCAT_PID" ]; then
		sudo -u $TOMCAT_USER sh $TOMCAT_BINDIR/shutdown.sh
		waitforit "shutdown" "INFO: Destroying ProtocolHandler "
		kill -9 $TOMCAT_PID
		cleanup
		test -f /ou/bin/kill_mysql_sessions.sh && \
			/ou/bin/kill_mysql_sessions.sh -f $PROPS
	else
		echo Tomcat pid not found, probably not running
	fi
  ;;

restart)
  $0 stop
  sleep $NAP
  $0 start
  ;;

cleanup)
	if [ -n "$TOMCAT_PID" ]; then
		echo Tomcat is running on pid $TOMCAT_PID, cannot cleanup
	else
		cleanup
	fi
  ;;

*)
	usage
	;;

esac
